[build]
  command = "ng build --configuration production"
  publish = "dist/my-resume-app/browser"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
